dist: trusty
language: rust
rust: stable
matrix:
  include:
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      env: TARGET=x86_64-apple-darwin
    - os: windows
      env: TARGET=x86_64-pc-windows-msvc
    - os: windows
      env: TARGET=x86_64-pc-windows-gnu
    - os: linux
      env: TARGET=i686-unknown-linux-gnu
    - os: windows
      env: TARGET=i686-pc-windows-msvc
    - os: windows
      env: TARGET=i686-pc-windows-gnu
before_script:
  - if [ "$TARGET" = i686-unknown-linux-gnu ]; then
      sudo apt-get update;
      sudo apt-get -y install gcc-multilib libc6-dev-i386;
    fi
script:
  - rustup default $TRAVIS_RUST_VERSION-$TARGET
  - cargo test --verbose --target=$TARGET
